version: '3'

services:
  node:
    build: .
    environment:
      IOP_GATEWAY: revad:19000
    volumes:
      - ./:/app/
    ports:
      - '3000:3000'
  revad:
    image: cs3org/revad:latest
    volumes:
      - './example/:/etc/revad/'
      - './example/tmp/:/var/tmp/'
    ports:
      - '19000:19000'